apiVersion: apps/v2
kind: Deployment
metadata:
  name: myfirstpythonapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myfirstpythonapp
  template:
    metadata:
      labels:
        app: myfirstpythonapp
    spec:
      containers:
      - name: myfirstpythonapp
        image: princessujay/myfirstpythonapp:0.0.2.RELEASE
        ports:
        - containerPort: 8000
