apiVersion: apps/v2
kind: Deployment
metadata:
  name: myfirstpythonapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myfirstpythonapp
  template:
    metadata:
      labels:
        app: myfirstpythonapp
    spec:
      containers:
      - name: myfirstpythonapp
        image: princessujay/myfirstpythonapp:0.0.2.RELEASE
        ports:
        - containerPort: 8000
        resources:
          limits:
            memory: "512Mi"
            cpu: "1000m"
          requests:
            memory: "256Mi"
            cpu: "500m"
