apiVersion: v2
kind: Service
metadata:
  name: myfirstpythonapp-service
spec:
  type: ClusterIP
  selector:
     app: myfirstpythonapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
