apiVersion: v1
kind: Service
metadata:
  name: myfirstpythonapp-service
spec:
  type: LoadBalancer
  selector:
     app: myfirstpythonapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
